apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-secrets
data:
  MISTRAL_API_KEY: {{ .Values.chatbot.secrets.api.MISTRAL_API_KEY | default "" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-registry-credential
data:
  .dockerconfigjson: {{ .Values.registry.secrets.dockerconfigjson | default "" | b64enc }}
type: kubernetes.io/dockerconfigjson
