apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
  labels:
    app: chatbot
    component: api
spec:
  type: ClusterIP
  selector:
    app: chatbot
    component: api
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-chat-service
  labels:
    app: chatbot
    component: chat
spec:
  type: ClusterIP
  selector:
    app: chatbot
    component: chat
  ports:
    - port: 8501
      targetPort: http
      protocol: TCP
      name: http
