#!/usr/bin/env sh

set -e

TAG="latest"

for arg in "$@"; do
  case "$arg" in
    --tag=*)
      TAG="${arg#--tag=}"
      ;;
    *)
      echo "Unknown argument: $arg"
      echo "Usage: $0 [--tag=<TAG>]"
      exit 1
      ;;
  esac
done

helm diff --allow-unreleased upgrade \
  chatbot ./chatbot \
  -n chatbot \
  --set chatbot.api.image.tag="$TAG"
